import type { Metadata } from "next";
import { Playfair_Display, Lato } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
const playfair = Playfair_Display({ subsets: ['latin'], variable: '--font-serif' })
const lato = Lato({ weight: ['300', '400'], subsets: ['latin'], variable: '--font-sans' })


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${playfair.variable} ${lato.variable}`}>
      <body className="font-sans">
        <Navbar/>
        {children}
        </body>
    </html>
  );
}
